/**
 * Formats the raid plan into a Discord Embed structure.
 * @param {Object} plan - The raid plan data.
 * @param {string} plan.game - Game name.
 * @param {string} plan.raid - Raid name.
 * @param {string} plan.vibe - 'Meme Chaos' or 'Serious Strat'.
 * @param {Array} plan.phases - Array of phase objects.
 * @returns {Object} Not compliant Discord webhook payload.
 */
export const formatRaidToEmbed = (plan) => {
    const isSerious = plan.vibe === 'Serious Strat';
    const color = isSerious ? 3447003 : 16724838; // Blue (#3498db) or Pink/Neon (#ff3366)

    // 1. Main Header Embed
    const mainEmbed = {
        title: `⚡ ${plan.game} // ${plan.raid}`,
        description: `**Operation Vibe:** ${plan.vibe}\nGenerated Plan for the squad.`,
        color: color,
        timestamp: new Date().toISOString()
    };

    // 2. Phase Embeds (One per phase to allow big images)
    const phaseEmbeds = plan.phases.map((phase, idx) => {
        const title = `Phase ${idx + 1}: ${phase.name}`;

        // Content: Full Generation Text + Quip/Tip + Roles
        let description = `**Action Plan:**\n${phase.text}\n\n`;

        if (isSerious) {
            description += `**Tactical Intel:** ${phase.quip}`;
        } else {
            description += `**Meme:** "${phase.quip}"`;
        }

        if (phase.roles && phase.roles.length > 0) {
            description += `\n\n**Squad assignments:** \`${phase.roles.join('`, `')}\``;
        }

        const embed = {
            title: title,
            description: description,
            color: color,
        };

        // Add Image if available
        if (phase.meme) {
            embed.image = { url: phase.meme };
        }

        return embed;
    });

    // Add Footer to the last embed
    if (phaseEmbeds.length > 0) {
        phaseEmbeds[phaseEmbeds.length - 1].footer = {
            text: "Generated by RaidMemeGen.vercel.app"
        };
    } else {
        mainEmbed.footer = {
            text: "Generated by RaidMemeGen.vercel.app"
        };
    }

    return {
        username: "RaidMemeGen Bot",
        avatar_url: "https://raidmemegen.vercel.app/logo192.png",
        embeds: [mainEmbed, ...phaseEmbeds]
    };
};

/**
 * Sends the payload to the Discord Webhook.
 * @param {string} webhookUrl 
 * @param {Object} payload 
 */
export const sendToDiscord = async (webhookUrl, payload) => {
    try {
        const response = await fetch(webhookUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            throw new Error(`Discord API Error: ${response.statusText}`);
        }
        return true;
    } catch (error) {
        console.error("Failed to send to Discord:", error);
        throw error;
    }
};
