import { forwardRef } from 'react';

const RaidExportTemplate = forwardRef(({ plan, userMap }, ref) => {
    if (!plan) return null;

    // Defined safe colors for html2canvas
    const colors = {
        bg: '#020617',       // gray-950
        cardBg: '#0f172a',   // gray-900
        border: '#1e293b',   // gray-800
        text: '#ffffff',     // white
        textDim: '#9ca3af',  // gray-400
        neon: '#00ff88',     // raid-neon
        accentBlue: '#3b82f6',
        accentPurple: '#a855f7'
    };

    return (
        <div
            ref={ref}
            style={{
                position: 'fixed',
                top: '-9999px',
                left: '-9999px',
                width: '1400px',
                backgroundColor: '#0f172a', // colors.bg from palette but hardcoded for safety
                color: '#ffffff',
                fontFamily: 'Inter, sans-serif',
                overflow: 'hidden',
                boxSizing: 'border-box',
                padding: '40px'
            }}
        >
            {/* Background Texture/Gradient */}
            <div style={{
                position: 'absolute',
                inset: 0,
                opacity: 0.1,
                backgroundImage: `radial-gradient(circle at 50% 50%, ${colors.neon} 0%, transparent 70%)`,
                backgroundSize: '100% 100%',
                pointerEvents: 'none'
            }}></div>

            <div style={{ position: 'relative', zIndex: 10 }}>
                {/* Header */}
                <div style={{ textAlign: 'center', paddingBottom: '32px', borderBottom: `1px solid ${colors.border}` }}>
                    <h1 style={{
                        fontSize: '64px',
                        fontWeight: 'bold',
                        fontFamily: 'Orbitron, sans-serif',
                        color: colors.neon,
                        textShadow: `0 0 20px ${colors.neon}`,
                        marginBottom: '16px',
                        marginTop: 0,
                        letterSpacing: '0.05em'
                    }}>
                        {plan.title.toUpperCase()}
                    </h1>
                    <p style={{ color: colors.textDim, fontSize: '24px', fontFamily: 'monospace', letterSpacing: '0.1em', margin: 0 }}>
                        OPERATION: {plan.game.toUpperCase()} // {plan.raid.toUpperCase()} // {plan.vibe.toUpperCase()}
                    </p>
                    <p style={{ color: '#6b7280', fontSize: '16px', marginTop: '12px', marginBottom: 0, fontFamily: 'monospace' }}>
                        GENERATED BY RAID MEME GEN
                    </p>
                </div>

                {/* Phases Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '32px', marginTop: '32px' }}>
                    {plan.phases.map((phase, idx) => (
                        <div key={idx} style={{
                            backgroundColor: 'rgba(15, 23, 42, 0.95)',
                            border: `1px solid ${colors.border}`,
                            borderRadius: '24px',
                            overflow: 'hidden',
                            display: 'flex',
                            height: '380px', // Adjusted height for better aspect ratio (wider look)
                            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.5)'
                        }}>
                            {/* Meme Side */}
                            <div style={{ width: '40%', position: 'relative', height: '100%', backgroundColor: '#000' }}>
                                {phase.meme ? (
                                    <img
                                        src={phase.meme}
                                        alt="Meme"
                                        style={{ width: '100%', height: '100%', objectFit: 'cover', opacity: 0.9 }}
                                        crossOrigin="anonymous"
                                    />
                                ) : (
                                    <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#374151', fontSize: '10px', fontFamily: 'Orbitron, sans-serif', padding: '10px', textAlign: 'center' }}>
                                        NO VISUAL
                                    </div>
                                )}
                                <div style={{
                                    position: 'absolute', inset: 0,
                                    backgroundImage: 'linear-gradient(to right, transparent, rgba(15, 23, 42, 0.95))'
                                }}></div>
                                <div style={{ position: 'absolute', bottom: '16px', left: '16px' }}>
                                    <span style={{
                                        backgroundColor: 'rgba(0, 0, 0, 0.9)',
                                        color: colors.neon,
                                        padding: '6px 10px',
                                        borderRadius: '6px',
                                        fontSize: '14px',
                                        fontWeight: 'bold',
                                        fontFamily: 'monospace',
                                        border: '1px solid rgba(0, 255, 136, 0.3)'
                                    }}>
                                        PHASE {idx + 1}
                                    </span>
                                </div>
                            </div>

                            {/* Content Side */}
                            <div style={{ width: '60%', padding: '32px', display: 'flex', flexDirection: 'column', height: '100%' }}>
                                <div style={{ flex: '0 1 auto', marginBottom: '16px' }}>
                                    <h3 style={{
                                        fontSize: '26px',
                                        fontWeight: 'bold',
                                        color: colors.text,
                                        marginBottom: '16px',
                                        lineHeight: '1.2',
                                        marginTop: 0
                                    }}>
                                        {phase.name}
                                    </h3>
                                    <p style={{
                                        color: '#cbd5e1',
                                        fontSize: '15px',
                                        lineHeight: '1.5',
                                        fontWeight: 400,
                                        display: '-webkit-box',
                                        WebkitLineClamp: 4,
                                        WebkitBoxOrient: 'vertical',
                                        overflow: 'hidden',
                                        margin: 0
                                    }}>
                                        {phase.text}
                                    </p>
                                </div>

                                {/* Roles Section */}
                                <div style={{ flex: '1 1 auto', overflow: 'hidden', marginBottom: '16px' }}>
                                    <div style={{ fontSize: '12px', fontWeight: 'bold', color: '#64748b', marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                                        MISSION ROLES
                                    </div>
                                    <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                                        {phase.assignments && Object.entries(phase.assignments).map(([role, userIds]) => {
                                            if (userIds.length === 0) return null;
                                            // Get names - Use userMap from props, not plan
                                            const names = userIds.map(uid => userMap?.[uid]?.username || 'Unknown Operator').join(', ');

                                            return (
                                                <div key={role} style={{
                                                    fontSize: '13px',
                                                    color: '#cbd5e1',
                                                    lineHeight: '1.4'
                                                }}>
                                                    <span style={{ color: colors.neon, fontWeight: 'bold', marginRight: '6px' }}>{role}:</span>
                                                    <span style={{ color: '#94a3b8' }}>{names}</span>
                                                </div>
                                            );
                                        })}
                                        {(!phase.assignments || Object.values(phase.assignments).every(arr => arr.length === 0)) && (
                                            <div style={{ fontSize: '11px', color: '#475569', fontStyle: 'italic' }}>
                                                No operatives assigned.
                                            </div>
                                        )}
                                    </div>
                                </div>

                                <div style={{ marginTop: 'auto', flexShrink: 0 }}>
                                    <div style={{ height: '1px', width: '100%', backgroundColor: colors.border, marginBottom: '12px' }}></div>
                                    <p style={{
                                        color: '#94a3b8',
                                        fontSize: '13px',
                                        fontStyle: 'italic',
                                        fontFamily: 'monospace',
                                        lineHeight: '1.4',
                                        margin: 0
                                    }}>
                                        "{phase.quip}"
                                    </p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Footer / Stats */}
                <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    backgroundColor: 'rgba(15, 23, 42, 0.5)',
                    padding: '24px',
                    borderRadius: '12px',
                    border: `1px solid ${colors.border}`,
                    marginTop: '40px'
                }}>
                    <div style={{ display: 'flex', gap: '32px' }}>
                        <div>
                            <span style={{ display: 'block', color: '#6b7280', fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>SQUAD SIZE</span>
                            <span style={{ fontSize: '24px', fontWeight: 'bold', color: colors.text }}>{plan.squadSize} OPERATIVES</span>
                        </div>
                        <div>
                            <span style={{ display: 'block', color: '#6b7280', fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>TOTAL TIME</span>
                            <span style={{ fontSize: '24px', fontWeight: 'bold', color: colors.neon }}>{plan.phases.reduce((acc, p) => acc + p.time, 0)} MINS</span>
                        </div>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                        <div style={{ fontSize: '24px', fontFamily: 'Orbitron, sans-serif', color: '#374151' }}>MEME RAID GEN</div>
                    </div>
                </div>
            </div>
        </div>
    );
});

export default RaidExportTemplate;
